phpbb.titania.index:
    pattern: /
    defaults: { _controller: phpbb.titania.controller.index:display_index }

phpbb.titania.faq:
    pattern: /faq
    defaults: { _controller: phpbb.titania.controller.faq:display_list }

phpbb.titania.queue_stats:
    pattern: /queue-stats/{contrib_type}
    defaults: { _controller: phpbb.titania.controller.queue_stats:display_stats }

phpbb.titania.support:
    pattern: /support/{type}
    defaults: { _controller: phpbb.titania.controller.support:display_topics, type: all }

phpbb.titania.all_contribs:
    pattern: /contributions/all
    defaults: { _controller: phpbb.titania.controller.all_contribs:display_all_contributions }
