imports:
    - { resource: controllers.yml }
    - { resource: cron.yml }
    - { resource: parameters.yml }

services:
    phpbb.titania.access:
        class: phpbb\titania\access
        arguments:
            - @dbal.conn
            - @user
            - @phpbb.titania.config

    phpbb.titania.config:
        class: phpbb\titania\config\config
        arguments:
            - @config
            - %phpbb.titania.root_path%
            - %core.php_ext%

    phpbb.titania.controller.helper:
        class: phpbb\titania\controller\helper
        arguments:
            - @template
            - @user
            - @config
            - @controller.provider
            - @ext.manager
            - @symfony_request
            - @request
            - @filesystem
            - %core.root_path%
            - %core.php_ext%

    phpbb.titania.cache:
        class: phpbb\titania\cache\service
        arguments:
             - @cache.driver
             - @config
             - @dbal.conn
             - %core.root_path%
             - %core.php_ext%

    phpbb.titania.display:
        class: phpbb\titania\display
        arguments:
             - @auth
             - @template
             - @user
             - @phpbb.titania.controller.helper
             - @path_helper

    phpbb.titania.style.demo.manager:
        class: phpbb\titania\contribution\style\demo\manager
        arguments:
            - @user
            - @service_container
            - @phpbb.titania.config
            - %core.php_ext%

    phpbb.titania.listener:
        class: phpbb\titania\event\main_listener
        arguments:
            - @user
            - @template
            - @phpbb.titania.controller.helper
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }

    phpbb.titania.queue.stats:
        class: phpbb\titania\queue\stats
        arguments:
            - @dbal.conn
            - @user
            - @template

