services:
    phpbb.titania.controller.index:
        class: phpbb\titania\controller\index
        arguments:
            - @auth
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.display
            - @phpbb.titania.cache
            - @path_helper

    phpbb.titania.controller.faq:
        class: phpbb\titania\controller\faq
        arguments:
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @phpbb.titania.display

    phpbb.titania.controller.queue_stats:
        class: phpbb\titania\controller\queue_stats
        arguments:
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.config
            - @phpbb.titania.display

    phpbb.titania.controller.support:
        class: phpbb\titania\controller\support
        arguments:       
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.display

    phpbb.titania.controller.all_contribs:
        class: phpbb\titania\controller\all_contribs
        arguments:
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.display
            - @path_helper

    phpbb.titania.controller.author:
        class: phpbb\titania\controller\author
        arguments:
            - @auth
            - @config
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.display
            - @phpbb.titania.config
            - @phpbb.titania.cache

    phpbb.titania.controller.download:
        class: phpbb\titania\controller\download
        arguments:
            - @dbal.conn
            - @auth
            - @user
            - @request
            - @phpbb.titania.controller.helper
            - @phpbb.titania.config
            - %core.root_path%
            - %core.php_ext%

    phpbb.titania.controller.contrib:
        class: phpbb\titania\controller\contribution\contribution
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.cache
            - @phpbb.titania.config
            - @phpbb.titania.display

    phpbb.titania.controller.contrib.support:
        class: phpbb\titania\controller\contribution\support
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.cache
            - @phpbb.titania.config
            - @phpbb.titania.display

    phpbb.titania.controller.manage:
        class: phpbb\titania\controller\manage\manage
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.cache
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.config
            - @phpbb.titania.display

    phpbb.titania.controller.manage.queue:
        class: phpbb\titania\controller\manage\queue\queue
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.cache
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.config
            - @phpbb.titania.display

    phpbb.titania.controller.manage.queue.item:
        class: phpbb\titania\controller\manage\queue\item
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @template
            - @user
            - @phpbb.titania.cache
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.config
            - @phpbb.titania.display
