services:
    phpbb.titania.controller.index:
        class: phpbb\titania\controller\index
        arguments:
            - @auth
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.display
            - @phpbb.titania.cache

    phpbb.titania.controller.faq:
        class: phpbb\titania\controller\faq
        arguments:
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @phpbb.titania.display

    phpbb.titania.controller.queue_stats:
        class: phpbb\titania\controller\queue_stats
        arguments:
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.config
            - @phpbb.titania.display

    phpbb.titania.controller.support:
        class: phpbb\titania\controller\support
        arguments:       
            - @template
            - @user
            - @phpbb.titania.controller.helper
            - @request
            - @phpbb.titania.display
