services:
    phpbb.titania.config:
        synthetic: true
    phpbb.titania.cache:
        class: phpbb\titania\cache\service
        arguments:
             - @cache.driver
             - @config
             - @dbal.conn
             - %core.root_path%
             - %core.php_ext%
    phpbb.titania.listener:
        class: phpbb\titania\event\main_listener
        arguments:
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
